version: '3.8'

services:      
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: database-name
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
    ports:
      - 5432:5432
    restart: on-failure:3
    networks:
      - shine

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    networks:
      - shine

networks:
  shine:
    external: true
