[package]
name = "shine-service"
version = "0.1.0"
authors = ["gzp <z.p.gaal@google.com>"]
edition = "2021"


[features]
default = ["ot_jaeger", "ot_zipkin", "ot_app_insight"]

ot_jaeger = ["opentelemetry-jaeger"]
ot_zipkin = ["opentelemetry-zipkin"]
ot_app_insight = ["reqwest", "opentelemetry-application-insights"]

[dependencies]
log = "0.4"
thiserror = "1.0"
config = "0.13"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

time = "0.3"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.3", features = ["v4", "serde"] }
base64 = "0.21"
hex = "0.4"
ring = "0.16"
primal-check = "0.3"
regex = "1.9"

futures = "0.3"
async-trait = "0.1"
tokio = {version = "1.27", features = ["macros", "rt-multi-thread", "signal"] }
rustls = "0.21"
rustls-pemfile = "1.0"
reqwest = { version = "0.11", optional = true }

validator = { version = "0.16", features = ["derive"] }
utoipa = { version = "3.4" }

bb8 = "0.8"
bb8-redis = "0.13"
redis = { version = "0.23.0", features = ["tokio-comp", "tokio-rustls-comp"] }
bb8-postgres = "0.8"
tokio-postgres = { version = "0.7", features = ["with-uuid-1", "with-chrono-0_4", "runtime"] }
tokio-rustls = "0.24"
tokio-postgres-rustls = "0.10"

azure_core = { version = "0.13" }
azure_identity = { version = "0.13" }
azure_security_keyvault = { version = "0.13" }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-opentelemetry = "0.19"
opentelemetry = { version = "0.19", features = ["rt-tokio"] }
opentelemetry-semantic-conventions = "0.11"
opentelemetry-jaeger = { version = "0.18", features = ["rt-tokio"], optional = true }
opentelemetry-zipkin = { version ="0.17", features = ["reqwest-client"], default-features = false, optional = true }
opentelemetry-application-insights = { version = "0.25", optional = true }

tower = "0.4"
axum = "0.6"
axum-extra = { version = "0.7", features = ["cookie", "cookie-signed", "cookie-private"] }
axum-tracing-opentelemetry = "0.12"

shine-macros = { path = "../shine-macros", version = "0.1.0" }

[dev-dependencies]
shine-test = { path = "../shine-test", version = "0.1.0" }